module.exports = {
  docs: [
    // {
    //   type: "autogenerated",
    //   dirName: ".",
    // },
    {
      type: "doc",
      id: "all",
    },
    {
      type: "doc",
      id: "timeline",
    },
  ],
};
