// const sidebarJson = require("./sidebars.json");

// module.exports = {
//   docsSidebar: [
//     // {
//     //   type: "doc",
//     //   id: "releases-notes",
//     // },
//     {
//       type: "category",
//       label: "Releases Notes",
//       items: ["all"],
//     },
//   ],
// };

module.exports = {
  docs: [
    // {
    //   type: "autogenerated",
    //   dirName: ".",
    // },
    {
      type: "doc",
      id: "all",
    },
    {
      type: "doc",
      id: "timeline",
    },
    // {
    //   type: "link",
    //   href: "/showcase",
    //   label: "Showcase",
    // },
    // {
    //   type: "link",
    //   href: "/feature-requests",
    //   label: "Feature Requests",
    // },
    // {
    //   type: "link",
    //   label: "Chat with us on Discord",
    //   href: "https://discord.gg/docusaurus",
    // },
  ],
};
