import React from "react";
import Link from "@docusaurus/Link";
import { useDocsData } from "@docusaurus/plugin-content-docs/client";
import semver from "semver/preload";

type ReleaseDoc = { id: string; path: string };

// Use actual release-note documents so newly added notes appear automatically,
// and links always use the paths generated by the release-notes plugin.
export function getReleaseSeriesNotes(docs: ReleaseDoc[], series: string) {
  return docs.flatMap((doc) => {
    const version = doc.id.match(/^versioned\/pulsar-(.+)$/)?.[1];
    const parsed = version ? semver.parse(version) : null;
    if (!parsed || `${parsed.major}.${parsed.minor}` !== series) {
      return [];
    }
    return [{ ...doc, version }];
  }).sort((a, b) => semver.rcompare(a.version, b.version));
}

export default function ReleaseSeriesNotes({ series }: { series: string }) {
  const { versions } = useDocsData("release-notes");
  const notes = getReleaseSeriesNotes(versions.flatMap(({ docs }) => docs), series);
  const latest = notes[0];

  if (!latest) {
    return null;
  }

  return (
    <>
      <p>
        Latest {series}.x release notes: {" "}
        <Link to={latest.path}>Apache Pulsar {latest.version}</Link>
      </p>
      {notes.length > 1 && (
        <details>
          <summary>All {series}.x release notes</summary>
          <ul>
            {notes.map((note) => (
              <li key={note.id}>
                <Link to={note.path}>Apache Pulsar {note.version}</Link>
                {note === latest && " (latest)"}
              </li>
            ))}
          </ul>
        </details>
      )}
    </>
  );
}
