import * as React from "react";

import Layout from "@theme/Layout";
import { getVersion, getApiVersion } from "../../utils/index.js";

import s from './RestApi.module.css';

function parseVersion(pathName) {
  let swagger = "swagger";
  if (pathName.indexOf("functions") > -1) {
    swagger = "swaggerfunctions";
  } else if (pathName.indexOf("source") > -1) {
    swagger = "swaggersource";
  } else if (pathName.indexOf("sink") > -1) {
    swagger = "swaggersink";
  } else if (pathName.indexOf("packages") > -1) {
    swagger = "swaggerpackages";
  } else if (pathName.indexOf("transactions") > -1) {
    swagger = "swaggertransactions";
  } else if (pathName.indexOf("lookup") > -1) {
    swagger = "swaggerlookup";
  }
  let version = getVersion();
  let apiversion = getApiVersion(swagger);

  if (version !== "master") {
    var versions = version.split(".");
    var majorVersion = parseInt(versions[0]);
    var minorVersion = parseInt(versions[1]);
    if (majorVersion < 2) {
      version = "2.3.0";
    } else if (minorVersion < 3) {
      version = "2.3.0";
    }
  }

  return [version, apiversion, swagger];
}

// Pulsar 5.0.0 (starting with 5.0.0-M1) and master publish OpenAPI 3 documents
// generated by the Gradle build; they need the Redoc 2.x bundle. Earlier
// releases keep their Swagger 2.0 documents and the legacy Redoc 1.x viewer.
function usesOpenApi3(version) {
  if (version === "master" || version === "next") {
    return true;
  }
  const major = parseInt(version.split(".")[0], 10);
  return !isNaN(major) && major >= 5;
}
class RestApi extends React.Component {
  componentDidMount() {
    let pathName = window.location.pathname;

    let [version, apiversion, swagger] = parseVersion(pathName);

    let params = window.location.search;
    params = params.replace("?", "");
    const paramsList = params.split("&");
    if (paramsList && paramsList.length > 0) {
      version = "master";
      apiversion = "";
      for (let i in paramsList) {
        let param = paramsList[i].split("=");
        if (param[0] === "version") {
          version = param[1];
        }
        if (param[0] === "apiversion" || param[0] === "apiVersion") {
          apiversion = param[1];
        }
      }
    }

    const wrapper = document.querySelector(".container");
    const redoc = document.createElement("redoc");
    redoc.setAttribute(
      "spec-url",
      "/swagger/" + version + "/" + apiversion + "/" + swagger + ".json"
    );
    const redocLink = document.createElement("script");
    if (usesOpenApi3(version)) {
      redocLink.setAttribute("src", "/js/redoc2.standalone.min.js");
    } else {
      redoc.setAttribute("lazy-rendering", "true");
      redocLink.setAttribute("src", "/js/redoc.min.js");
    }
    const script = document.querySelector(".container script");
    wrapper.insertBefore(redoc, script);
    wrapper.insertBefore(redocLink, script);
  }

  render() {
    return (
      <Layout>
        <div className={s.container}>
          <div className="my-12 container"></div>
        </div>
      </Layout>
    );
  }
}

export default RestApi;
