import * as React from "react";

import Layout from "@theme/Layout";
import { getVersion, getApiVersion } from "../../utils/index.js";

import s from './RestApi.module.css';

function parseVersion(pathName) {
  let swagger = "swagger";
  if (pathName.indexOf("functions") > -1) {
    swagger = "swaggerfunctions";
  } else if (pathName.indexOf("source") > -1) {
    swagger = "swaggersource";
  } else if (pathName.indexOf("sink") > -1) {
    swagger = "swaggersink";
  } else if (pathName.indexOf("packages") > -1) {
    swagger = "swaggerpackages";
  } else if (pathName.indexOf("transactions") > -1) {
    swagger = "swaggertransactions";
  } else if (pathName.indexOf("lookup") > -1) {
    swagger = "swaggerlookup";
  }
  let version = getVersion();
  let apiversion = getApiVersion(swagger);

  if (version !== "master") {
    var versions = version.split(".");
    var majorVersion = parseInt(versions[0]);
    var minorVersion = parseInt(versions[1]);
    if (majorVersion < 2) {
      version = "2.3.0";
    } else if (minorVersion < 3) {
      version = "2.3.0";
    }
  }

  return [version, apiversion, swagger];
}

// Pulsar 5.0.0 (starting with 5.0.0-M1) and master publish OpenAPI 3 documents
// generated by the Gradle build; they need the Redoc 2.x bundle. Earlier
// releases keep their Swagger 2.0 documents and the legacy Redoc 1.x viewer.
function usesOpenApi3(version) {
  if (version === "master" || version === "next") {
    return true;
  }
  const major = parseInt(version.split(".")[0], 10);
  return !isNaN(major) && major >= 5;
}

// Each REST API is published as its own Redoc viewer page (one OpenAPI document
// each). This list drives the toolbar dropdown that lets readers jump between
// them; labels mirror docs/reference-rest-api-overview.md.
const REST_APIS = [
  { label: "Admin", slug: "admin-rest-api" },
  { label: "Functions", slug: "functions-rest-api" },
  { label: "Sources", slug: "source-rest-api" },
  { label: "Sinks", slug: "sink-rest-api" },
  { label: "Packages", slug: "packages-rest-api" },
  { label: "Transactions", slug: "transactions-rest-api" },
  { label: "Lookup", slug: "lookup-rest-api" },
];

class RestApi extends React.Component {
  componentDidMount() {
    let pathName = window.location.pathname;

    let [version, apiversion, swagger] = parseVersion(pathName);

    let params = window.location.search;
    params = params.replace("?", "");
    const paramsList = params.split("&");
    if (paramsList && paramsList.length > 0) {
      version = "master";
      apiversion = "";
      for (let i in paramsList) {
        let param = paramsList[i].split("=");
        if (param[0] === "version") {
          version = param[1];
        }
        if (param[0] === "apiversion" || param[0] === "apiVersion") {
          apiversion = param[1];
        }
      }
    }

    const wrapper = document.querySelector(".container");
    const redoc = document.createElement("redoc");
    const openApi3 = usesOpenApi3(version);
    // Pulsar 5.0.0+/master publish OpenAPI 3 documents under /openapi/ with
    // "openapi*.json" file names; pre-5.0 releases keep their Swagger 2.0
    // documents under /swagger/ with "swagger*.json" file names.
    const specDir = openApi3 ? "/openapi/" : "/swagger/";
    const specFile = (openApi3 ? swagger.replace("swagger", "openapi") : swagger) + ".json";
    // Only insert the REST API version segment (v2/v3) when it is known; the
    // doc links that omit it resolve to the flat spec file at the version root.
    const specUrl = apiversion
      ? specDir + version + "/" + apiversion + "/" + specFile
      : specDir + version + "/" + specFile;
    const redocLink = document.createElement("script");
    if (openApi3) {
      // The redoc2 standalone auto-init only honors the spec-url attribute and
      // discards every other option, so initialize Redoc explicitly. This lets
      // us set downloadFileName: the spec saved by Redoc's download button is
      // named after the Pulsar version rather than the internal "openapi*.json".
      redocLink.setAttribute("src", "/js/redoc2.standalone.min.js");
      redocLink.onload = () => {
        (window as any).Redoc.init(
          specUrl,
          { downloadFileName: "pulsar_openapi_spec_" + version + ".json" },
          redoc
        );
      };
    } else {
      redoc.setAttribute("spec-url", specUrl);
      redoc.setAttribute("lazy-rendering", "true");
      redocLink.setAttribute("src", "/js/redoc.min.js");
    }
    // Toolbar with a button that expands the Redoc view to the full page width
    // by dropping the Docusaurus container max-width (see .fullWidth in the CSS
    // module). The wide three-pane REST API layout is otherwise cropped by the
    // centered content column.
    const toolbar = document.createElement("div");
    toolbar.className = s.toolbar;
    const expandButton = document.createElement("button");
    expandButton.type = "button";
    expandButton.className = "button button--secondary button--sm";
    expandButton.title = "Toggle full-width view";
    const collapsedLabel = "⤢ Full width";
    const expandedLabel = "⤡ Exit full width";
    expandButton.textContent = collapsedLabel;
    expandButton.onclick = () => {
      const expanded = wrapper.classList.toggle(s.fullWidth);
      expandButton.textContent = expanded ? expandedLabel : collapsedLabel;
      // Nudge Redoc to recompute its responsive (menu / samples pane) layout
      // for the new width.
      window.dispatchEvent(new Event("resize"));
    };
    // Dropdown (left of the Full width button) to jump between the per-API Redoc
    // viewer pages, preserving the ?version= selection.
    const apiSelect = document.createElement("select");
    // Render the native <select> like the adjacent Full width button.
    apiSelect.className = "button button--secondary button--sm " + s.apiSelect;
    apiSelect.title = "Jump to another REST API";
    const currentApi = REST_APIS.find((a) =>
      window.location.pathname.includes(a.slug)
    );
    for (const api of REST_APIS) {
      const option = document.createElement("option");
      option.value = api.slug;
      option.textContent = api.label;
      option.selected = !!currentApi && api.slug === currentApi.slug;
      apiSelect.appendChild(option);
    }
    apiSelect.onchange = () => {
      const slug = apiSelect.value;
      const pathname = currentApi
        ? window.location.pathname.replace(currentApi.slug, slug)
        : "/" + slug + "/";
      // Keep ?version= but drop apiVersion: it is per-API and recomputed by the
      // target page.
      const search = new URLSearchParams(window.location.search);
      search.delete("apiversion");
      search.delete("apiVersion");
      const query = search.toString();
      window.location.assign(pathname + (query ? "?" + query : ""));
    };

    toolbar.appendChild(apiSelect);
    toolbar.appendChild(expandButton);

    const script = document.querySelector(".container script");
    wrapper.insertBefore(toolbar, script);
    wrapper.insertBefore(redoc, script);
    wrapper.insertBefore(redocLink, script);
  }

  render() {
    return (
      <Layout>
        <div className={s.container}>
          <div className="my-12 container"></div>
        </div>
      </Layout>
    );
  }
}

export default RestApi;
